name: test
on:
  pull_request:
    types: [opened, synchronizem reopened]
jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app && /usr/bin/xcodebulild -version

      - name: Run Tests
        run:  xcodebuild -project DisneyCharacters.xcodeproj -scheme DisneyCharacters -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' test